### ISSUE TITLE
Hosts with non bound ports are not accessible through VPN

### ISSUE THREAD

**Issue by phutchins** [wojas/docker-mac-network#4]
First, this is a great project! Wonderful approach to get around the problem that we have on OSX currently. 

My problem is that I want to be able to do a docker-compose scale against one of my services. This service needs to have a static port and a different IP for each. I can't map the port to OSX because there would then be conflicts. I cannot make this a random port because the app must know what port and IP it's serving on so that it can announce it and be reached. 

VPN is a perfect solution for this however, when I try to access any of the hosts that do not have mapped ports, I cannot reach them. 

I tracked the issue down to the fact that there are firewall rules on the docker VM that only allow traffic to hosts that have mapped ports and drop all other traffic. 

I assume that these rules were created by docker. 

I was able to fix the issue by adding a few rules from within the OpenVPN container (against the docker host). I don't' want to have to do this manually or programmatically for every service so I'd like to automatically open up the interface on start of the VPN. 

My plan is to add a rule or rules to the OpenVPN container startup that will allow this traffic. I'm not sure if docker will try to overwrite these changes however and am wondering if there is a better way.

Any thoughts?

**Comment by phutchins** [comment]
I found a solution for this but am working on making it less manual and more elegant... Had to make some tweaks to the docker vm's iptables. Will share the solution when it's tidied up.

**Comment by wojas** [comment]
@phutchins For this you can simply expose each service on a random port. The service will still be reachable on the original port at the internal container IP. The random port only applies to port forwarding on the host interface. The port within the container is not affected.

For example, if you expose port 80 with `ports: ["80"]`, it will be assigned a random port on your macOS localhost, but you can still reach this service at something like`172.20.0.10:80` through the VPN and from other containers within the same Docker network.

**Comment by phutchins** [comment]
@wojas awesome! This is a much cleaner solution and is built into docker... Didn't realize that exposing a random port would create the iptables rules so thats perfect. I've tried it out and it works quite nicely.

I'd like to build this into a generic opensource framework for project development... One of the other things that I'd like to accomplish with it is exposing hosts over the VPN via DNS by their hostname. Have you used any of the existing solutions for DNS in docker/docker-compose by chance?

**Comment by wojas** [comment]
@phutchins I have not used any third party solution to also expose DNS on the macOS host (not aware of any), but it is an interesting idea.

One possible approach would be to use PowerDNS recursor or dnsdist's Lua support to resolve against Docker APIs for say a .docker TLD (and hope that this TLD won't get registered in the future), while passing through normal queries.

This can only work with one VPN connection, or if you use a special DNS container just for this.

**Comment by wojas** [comment]
I'm closing this issue, as it works out of the box with exposed ports.

**Comment by phutchins** [comment]
Thanks for the feedback, I'll let you know what I end up doing. And sounds good on closing this!
