### ISSUE TITLE
Can't access containers in the internal Docker bridge network

### ISSUE THREAD

**Issue by domientje** [wojas/docker-mac-network#6]
I've tried running the current version but I can't connect to my other running docker containers through the internal Docker IPs.

After tracking down the issue, it seems that starting the openvpn container in host network mode is the culprit. I've forked the repo and made some changes so that openvpn runs in bridge network mode (and also removed the proxy container since it's not really needed) and now it works!

If you are interested I can make a pull request?

**Comment by wojas** [comment]
Hi, I am surprised you are not able to connect to the containers. The whole reason OpenVPN is started in host mode with a separate proxy is to be able to access all the Docker networks within the VM. If you put it on a bridge network, I think you will not be able to access other Docker networks created by Docker Compose.

**Comment by wojas** [comment]
I just tested it, and I can confirm this bug.

A quick workaround is running `iptables -I FORWARD 1 -i tun+ -j ACCEPT` within the VM (I use `docker run -it -v /:/mnt --pid=host --privileged --net=host alpine chroot /mnt` to get a shell there).

I am curious about your pull request. :-)

**Comment by wojas** [comment]
Closing this issue, as I believe the change resolves the issue.
